language: go
go:
  - 1.13.x
go_import_path: github.com/harrietty/conju_api
branches:
  only:
    - master
    - dev
install: "./install-dependencies.sh"
build:
  - make build
deploy:
  - provider: script
    skip_cleanup: true
    script: make deployprod
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: make deploy
    on:
      branch: dev
notifications:
  slack:
    on_success: always
    on_failure: always
    rooms:
      - secure: 2qmtE/ynRrpBdUidQYHjIchQNwSLck7JReG4PQY+Tjlv2RL/OdsaCdIRjMj+F4+8YOgeKwjCRnrkRSENp7qdIgKMbcvSrnyfpc3tnCcN03CrhqWmT347PnaxnwNQlxnas0V/VfLmD2TwEZRf21Hc3rQkBC9uT6hycyiXCLC4JHEW2sFaE8ja58PumJgaCCFRCuuF4lxPTuqunCeIZJDYdgVLg7el5+LghUUv3YRMgT/LRuEmfVwnkc0qjy/DcmRtWhZKtQUdmJRBA4MNzATSEGxovoh7hI3EDfoKsejtMxXI5pTQvtP2uLYAejHYe/8jaZag/nYsJPgidt7qLzyBwnG6WIjDAdm7ItqIRivdAvWQ5PRo86TSxM0VEIJ1Bj2+AeYmaR6KMDlqf9vNxkpBR0XU/RgkFwhyvQoMLNS7jh4oMxD0wMEjfYQ2DL0SbaTGq7QWxwCWYtrL/H7xL/CDE8B8AeYZcOU1qNV+YsRsXXv3B8LSPM3u2s69hJTsWvckmU6l2xGPG9n9VjCTiNl4kGzuPOpIcvHI7/2f8iT4eJ8/49MeVb2beFMYlZc2/nY4glewm8VjsawWNXdSkzeWS8zNYwxFVDHJCzwaOHNSl/2YzrB/dApS/yImYuyVywWWAT3kZRKi5xil/xsALcny2/Q9ugrGs3uAbx5NHfFpUek=
