service: conju-api
frameworkVersion: ">=1.28.0 <2.0.0"

provider:
  name: aws
  runtime: go1.x
  region: eu-west-1
  stage: dev

custom:
  stage: ${opt:stage, self:provider.stage}

  package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  infinitives:
    handler: bin/infinitives
    environment:
      STAGE: ${self:custom.stage}
    events:
      - http:
          path: infinitives
          method: get
          cors: true
