service: conju-api
frameworkVersion: ">=1.28.0 <2.0.0"
provider:
  name: aws
  runtime: go1.x
  region: eu-west-1

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  verbs:
    handler: bin/get_verbs
    events:
      - http:
          path: verbs
          method: get
